### ISSUE TITLE
Convert tabs to spaces

### ISSUE THREAD

**Issue by berksaribas** [aburakayaz/guessing-game-server-client#3]
All the tabs in the project should be converted to spaces. Instead of a tab there should be 4 spaces.

**Comment by AshwatKumar** [comment]
In project , you mean , in EACH and EVERY file of the project ?

**Comment by berksaribas** [comment]
@AshwatKumar I mean every .java file.

**Comment by semajthomasprimm** [comment]
Would a JavaFX program that looks in a folder and modifies every .java file be sufficient?

**Comment by berksaribas** [comment]
@semajthomasprimm no need to create a JavaFX program. You can open the project in a code editor, change the indention settings and reformat the code.
